feat(podman): run podman tests in ubuntu and macos

diff --git a/.github/actions/podman-setup/action.yml b/.github/actions/podman-setup/action.yml
--- a/.github/actions/podman-setup/action.yml
+++ b/.github/actions/podman-setup/action.yml
@@ -1,14 +1,35 @@
 name: "Podman Setup"
 description: "Sets up Podman"
+inputs:
+  runner:
+    description: "The runner type (e.g., macos-latest, ubuntu-latest)"
+    default: ubuntu-latest
+    required: true
 runs:
   using: "composite"
   steps:
+    - name: Podman constraints
+      shell: bash
+      run: |
+        if [[ ! "${{ inputs.runner }}" =~ ^macos.* || "${{ inputs.runner }}" =~ ^ubuntu.* ]]; then
+          echo "::error::Podman is only supported on macOS and Ubuntu"
+          exit 1
+        fi
     - name: Podman setup
       shell: bash
+      if: ${{ inputs.runner == 'ubuntu-latest' }}
       run: |
         curl -fsSL "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_$(lsb_release -rs)/Release.key" | gpg --dearmor | sudo tee /etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg > /dev/null
         echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg] https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_$(lsb_release -rs)/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list > /dev/null
         sudo apt-get update
         sudo apt-get -y install podman
         systemctl enable --now --user podman podman.socket
+        podman info
+    - name: Podman setup (macOS)
+      shell: bash
+      if: ${{ inputs.runner == 'macos-latest' }}
+      run: |
+        brew install podman
+        podman machine init
+        podman machine start
         podman info
